---

- name: Create a {{ application_name }} virtual machine via ansible
  hosts: vcl-webservers
  become: yes

  vars:
    - update_apt_cache: yes
    - project_name: vcl-dashboard
    - application_name: vcl
  vars_files:
    - env_vars/base.yml

  roles:
    - web
